// Long-form body copy per industry — written for San Antonio context.
// Used by industry.$slug.tsx to lift pages above the 700-word threshold.
// Mock copy while INDEXABLE=false; the owner can edit freely.

export const INDUSTRY_BODIES: Record<string, string[]> = {
  construction: [
    "San Antonio is one of the most active construction markets in Texas. Population growth across the I-35 corridor, ongoing public-works build-out across Bexar County, a steady pipeline of multifamily and tenant-improvement work in Stone Oak and Northside, plus the long industrial build-out at Port San Antonio and the Toyota corridor on the South Side. Contractors here finance a different mix of projects than the national average — more public-works tie-ins, more multifamily and more industrial fit-out.",
    "Anchor Capital Group routes construction financing across three distinct buckets. Equipment loans cover trucks, lifts and field equipment with the gear as collateral — usually the fastest path. Construction business loans fund actual ground-up and major rehab projects on a multi-draw basis tied to milestones. SBA 7(a) and 504 loans handle owner-occupied yard or office purchases and acquisitions of competing contractors. AR financing covers the gap between AIA progress payments and weekly payroll. The right product depends on the contractor's stage and the use of funds.",
    "Most established San Antonio contractors with bonded experience qualify for at least three of those four products. Newer contractors (under three years in business) usually start with equipment financing and a small revolving line, then layer in larger structures as books and bonding capacity grow. We pre-screen lenders specifically for Texas contractor profiles — including TDLR-relevant verifications and surety-bonded operator considerations that general business lenders often miss.",
  ],
  healthcare: [
    "Healthcare in San Antonio spans dental, medical, behavioral health, urgent care, surgery centers, imaging, DME suppliers and senior care. The local provider ecosystem is anchored by Methodist, Baptist, the University Health System, the South Texas Medical Center cluster, JBSA-area military medicine, and a deep bench of Stone Oak and Alamo Heights independent practices. Each segment has a different best-fit lender pool and underwriting playbook.",
    "Practice acquisitions — buying into a partnership, acquiring a retiring provider's practice or rolling up multiple locations — are usually the highest-stakes financing decision a provider makes. SBA 7(a) can fund up to 90% of acquisition value with practice cash flow as primary collateral. Specialty practice-lending banks (a handful of national players) compete aggressively with SBA on rate and speed for the strongest profiles, offering streamlined structures for dental, medical and veterinary.",
    "Beyond acquisitions, San Antonio healthcare providers finance equipment (CBCT scanners, CT/MRI, surgical platforms, dental chairs), real estate (buying the medical office building you currently lease — often the highest-NPV move a mature practice makes) and working capital (smoothing payer reimbursement gaps). Anchor matches the product to the provider stage, payer mix and operating model.",
  ],
  hospitality: [
    "San Antonio hospitality runs on event volume — the Riverwalk, Convention Center bookings, Spurs season, Fiesta, USAA-driven business travel and the steady tourism pull of the Alamo and Pearl. Operators across Downtown, Pearl, Southtown and the I-35 hotel corridor share a single financing challenge: how to size capital structure around revenue that is genuinely seasonal and event-driven rather than monthly-flat.",
    "Acquisition financing — buying an existing restaurant or flagged hotel — is usually the easiest path to SBA 7(a) approval because trailing financials and equipment are already in place. SBA Preferred Lenders with active hospitality desks can close acquisitions in 45-60 days at competitive rates. Ground-up new builds and conversions are harder; lenders want a clear lease, capable operator, and proof-of-concept in operator history or sister-location performance.",
    "Equipment financing handles kitchen, hood, FF&E and POS upgrades with the equipment as collateral. Working capital lines and short-term loans handle inventory, payroll and shoulder-season bridges. Merchant cash advances are a last-resort tool when other products are off the table. Anchor is direct about which products fit which operator stage rather than promising every operator the same SBA-grade rate.",
  ],
  transportation: [
    "San Antonio sits at the intersection of I-10 and I-35 — between Houston, Austin and the Mexican border — making it one of the most freight-dense markets in the country. The transportation businesses operating here (drayage carriers running cross-border, regional trucking fleets, freight brokers, oilfield-services rolling stock and 3PL distribution operators) finance a distinctive mix of assets and working capital that general lenders rarely understand correctly.",
    "Tractors and trailers finance as equipment loans — usually 10-20% down with 48-72 month terms, secured by the unit. Carriers operating between net-30 and net-90 broker terms use invoice factoring or AR financing to bridge the cash gap; for established carriers, AR lines materially beat factoring on cost. Operating-authority startups (drivers who just got their MC number) have the tightest funding options outside personal credit and equipment-only loans.",
    "Anchor routes South Texas transportation deals across all three stages. Owner-operators usually need equipment financing plus a small working capital cushion. Established 5-50 truck fleets qualify for AR lines, equipment refinancing at lower rates than original purchase pricing, and SBA-backed real estate loans for yard purchases. Larger operators add 401(k) ROBS structures, M&A facilities, and asset-based lending against rolling stock and receivables combined.",
  ],
  retail: [
    "San Antonio retail clusters across distinct districts — boutique-heavy at the Pearl, the Broadway corridor through Alamo Heights, North Star and La Cantera large-format, neighborhood retail along Bandera and Broadway, and the legacy independent storefronts along Westside Commerce. Each district has different rent levels, foot-traffic patterns and customer demographics, which means different cash-flow profiles and different best-fit financing.",
    "Inventory-heavy retailers (apparel, gift, specialty grocery, furniture) benefit most from revolving lines of credit that flex with seasonal buying cycles — pay down after holiday sell-through, draw up before the next buy. Service-flavored retail (salons, fitness, repair) lean more on SBA-backed build-out and equipment financing. Specialty high-margin retail (jewelry, art, high-end electronics) can sometimes pledge inventory as collateral for asset-based lines at attractive pricing.",
    "Acquisition financing matters in San Antonio retail because established locations in the Pearl and the Broadway corridor rarely come up on the open market. SBA 7(a) handles those acquisitions when they happen — buying an existing retailer with goodwill and inventory rather than building from scratch in an unproven location. Anchor has routed financing for boutique handoffs, family-business successions and franchise unit acquisitions across the districts.",
  ],
  manufacturing: [
    "Manufacturing in San Antonio is anchored by the Toyota Texas truck plant, the Tier-2 supplier base feeding it from the South Side and Westside, Port San Antonio aerospace fabricators, food and beverage producers throughout the metro, and a deep base of Westside legacy operators in metal-bending, fabrication and family food production.",
    "Equipment financing dominates the manufacturing pipeline — CNC machines, stamping presses, robotics, conveyor systems and full production cells. The equipment is the collateral, and the structure aligns to the ROI timeline of the asset. Working capital lines bridge raw-material spikes and large customer POs. AR factoring or AR financing covers the gap between OEM payment cycles and weekly operating cost.",
    "Anchor pre-screens by sub-sector and customer concentration. A Tier-2 stamping shop feeding Toyota is a different lender profile than a food producer selling through HEB, and both differ from a Port SA aerospace MRO billing federal primes. The right lender for each lives in a different corner of the equipment-finance and AR-lending bench.",
  ],
  "professional-services": [
    "Professional services in San Antonio — law firms, accounting practices, consulting groups and partner-led firms — concentrate in Downtown, Alamo Heights and the Stone Oak / North Side professional corridors. Operators here are typically partnership-owned, asset-light and partner-comp-driven, which means the standard SBA-and-equipment toolkit fits poorly and unsecured / revenue-aligned structures fit much better.",
    "The dominant products for established professional firms are unsecured working capital lines, partner buy-in loans against future distributions, and revenue-based financing for growth investments that don't fit on an equipment-loan structure. SBA 7(a) still fits when a firm is acquiring another practice or partner book. Real estate purchases through SBA 504 fit when a firm finally buys out its Downtown or Alamo Heights office.",
    "Anchor pre-screens for unsecured-friendly lenders within the SBA Preferred Lender pool and the broader specialty bench, rather than running you through general underwriting that demands collateral a professional services firm doesn't have.",
  ],
  "oilfield-services": [
    "Oilfield services in South Texas — based out of San Antonio and supplying the Eagle Ford basin and the Permian — run on rig-count revenue. When rig count is up, lenders are aggressive; when it's down, even profitable service operators face tighter terms. Anchor Capital Group structures financing with that cycle in mind rather than treating oilfield like generic small business lending.",
    "The dominant products are equipment financing (rolling stock, pumps, trailers with the gear as collateral), AR factoring or AR financing to bridge the 60-90 day E&P payment cycle that strangles weekly payroll, and working capital lines for slow quarters. SBA 7(a) can fit acquisitions and partner buy-outs for established service companies with three years of clean financials.",
    "We pre-screen by basin exposure (Eagle Ford vs. Permian vs. cross-basin), customer concentration and asset base. The right lender for a single-basin pressure-pumping operator isn't the right lender for a diversified mid-size service company billing multiple primes.",
  ],
  "defense-aerospace": [
    "San Antonio is Military City USA — Joint Base San Antonio (Lackland, Randolph, Fort Sam), Port San Antonio (the redeveloped Kelly AFB) and a deep base of MRO, defense IT, cleared services and veteran-owned operators. Defense and aerospace financing here has its own toolkit because the receivables behave differently than commercial AR.",
    "AR financing against federal and prime-contractor receivables works cleanly with lenders comfortable with FAR-billed invoices. Contract mobilization working capital covers the gap between contract award and first invoice clearing. SBA Express for veteran-owned businesses offers reduced fees and 36-hour SBA turnaround — meaningful for cleared operators bidding on time-sensitive task orders.",
    "Anchor pre-screens for veteran-friendly and defense-savvy lenders within the SBA Preferred bench and the broader AR-financing market. Translating clearance, contract vehicle and prime-relationship strength into underwriting language is most of the work on these files.",
  ],
  distribution: [
    "Distribution and logistics in San Antonio cluster along the I-35 NE corridor between San Antonio and Austin (Amazon, Sysco, broad 3PL base), Port San Antonio for aerospace logistics, and the South Side for cross-border and Toyota-corridor distribution. Operators here finance the same general mix as transportation, with more emphasis on warehouse equipment and racking and less on rolling stock.",
    "AR financing or AR factoring covers the gap between large-customer payment cycles and weekly operating cost. Equipment financing handles racking, forklifts, conveyors and material-handling equipment with the gear as collateral. Revenue-based financing fits 3PLs scaling through peak season without taking on fixed monthly installments. SBA 504 fits owner-occupied warehouse real estate purchases.",
    "Anchor routes by customer concentration and asset base. The right lender for a 3PL with one big-box customer is different from the right lender for a freight broker with 200 active shippers, even though both are technically \"distribution\".",
  ],
};
