// Long-form body copy per pillar - written for Nashville context.
// Used by pillar.$slug.tsx to lift pages above the 700-word threshold.
// Mock copy while INDEXABLE=false; the owner can edit freely.

export const PILLAR_BODIES: Record<string, string[]> = {
  "accounts-receivable-financing": [
    "Accounts receivable financing - sometimes called an AR line or asset-based lending - lets Nashville businesses borrow against unpaid customer invoices instead of waiting net-30, net-60 or net-90 for collection. It is a revolving facility: as new invoices age in, they become collateral; as old invoices get paid, the line replenishes. For staffing firms, logistics operators, oilfield services and government contractors operating out of Middle Tennessee, that's a fundamentally better structure than a fixed-term loan.",
    "The right fit is a B2B operator with creditworthy customers - BNA corridor tenants billing federal primes, 3PLs along the I-65 corridor billing big-box retailers, industrial services crews billing Tier-1 primes on 60-90 day terms. Advance rates run 80-90% of eligible invoice value. Pricing is typically 1-3% per month on the outstanding balance, materially better than factoring at consistent volume. Foxglove Lenders pre-screens by customer concentration, invoice aging and industry - staffing, freight and government contracting each have specialty AR financiers worth shopping rather than starting from a generalist line.",
  ],
  "invoice-factoring": [
    "Invoice factoring is a sale, not a loan: you sell unpaid invoices to a factor at a discount (typically 1-5% of face value) and the factor collects directly from your customer. For Nashville trucking companies running the I-65 freight corridor, staffing firms and B2B service businesses with strong invoices but cash-flow gaps, factoring can be a more sustainable structure than recurring short-term loans.",
    "Unlike AR financing, factoring doesn't appear as debt on your balance sheet. Your customers pay the factor directly. The trade-off is the customer-facing relationship - they will know you factor. For some industries that's invisible (freight, oilfield services, staffing). For others it can be a concern (consulting, professional services). We help identify which factors specialize in your industry and offer non-notification options where available.",
  ],
  "revenue-based-financing": [
    "Revenue-based financing (RBF) takes a fixed percentage of monthly revenue until a pre-agreed total cap is repaid. Unlike a fixed-payment loan, your remittance flexes with your sales: slow months mean smaller payments, busy months mean faster payoff. For Nashville SaaS firms in the Midtown corridor, hospitality operators around Lower Broadway, and seasonal businesses out in Franklin, that flexibility is often the difference between manageable and crushing debt service.",
    "RBF is not free: total payback usually runs 1.2x to 1.5x of funded amount, which on an annualized basis is more expensive than bank debt. The product is right when your business has strong revenue growth, no collateral to pledge, and predictable seasonality. It's wrong when you have access to bank or SBA funding at half the cost. Foxglove Lenders models both before recommending.",
  ],
  "small-business-loans": [
    "\"Small business loan\" is an umbrella term. For Nashville businesses doing under $5M in revenue, the real choices are: an SBA 7(a) loan (lowest rate, slowest), a bank term loan (mid-rate, mid-speed, harder to qualify), a non-bank term loan (faster, higher rate, easier to qualify), or a line of credit (flexible, revolving). The right product depends on what the money is for and how fast it has to land.",
    "We start every small business loan conversation with three questions: how much, what for, and how soon. The answers usually map cleanly to one or two real options. Pre-qualifying takes 60 seconds and a soft credit pull - no hit to your score, no obligation, and a clear picture of the funding range you'd qualify for today.",
  ],
  "small-business-loans-near-me": [
    "\"Small business loans near me\" is one of the most-searched local finance queries in Nashville, and one of the most misunderstood. Local proximity used to matter when small business loans came from neighborhood bank branches. Today, the lender most likely to fund your deal might be headquartered in Dallas, Atlanta or New York. What matters is product fit and industry expertise, not zip code.",
    "Foxglove Lenders operates locally. Nashville is our service area and we know which lenders fund I-24 / I-65 distribution, Green Hills medical, The Gulch hospitality and BNA corridor industrial. Our advantage isn't a branch nearby - it's a curated network of national and regional lenders matched to local business profiles. You'll work with the right lender for your deal, not just the closest one.",
  ],
  "sba-loans": [
    "Nashville businesses use SBA financing for two situations that almost nothing else solves cleanly: buying the real estate they currently lease, and acquiring a competitor or retiring owner's book of business. SBA 7(a) and 504 programs combine 10% to 15% down, terms up to 25 years on real estate, and rates pegged to Prime - so the monthly payment usually beats whatever the seller's note would have looked like.",
    "The catch is paperwork. SBA applications want three years of tax returns, current interim financials, a personal financial statement for every 20%-plus owner, debt schedules and a clear use-of-funds memo. Foxglove Lenders routes the file to the SBA Preferred Lender in our network most likely to approve your specific profile. Green Hills dental practices, The Gulch restaurant groups, Nashville Airport (BNA) corridor tenants and East Nashville legacy operators each have different best-fit banks.",
  ],
  "working-capital-loans": [
    "Working capital loans bridge a specific shortfall - payroll for the next two weeks, an inventory purchase order due Friday, a vendor demanding payment before they release the next shipment. They are not a long-term financing instrument and they should not be treated like one. Typical terms run 6 to 18 months with daily or weekly remittance, which keeps the math honest: if the cash flow does not generate the payment, you find out fast.",
    "We see Nashville restaurants in 12 South, retailers along Lower Broadway, contractors in South Nashville and distribution crews use working capital advances most often. The right fit comes down to factor rate, prepayment discount and whether the lender stacks (most we work with do not). A 5-minute call narrows the field to one or two real options.",
  ],
  "business-line-of-credit": [
    "A revolving line of credit is the right tool when your Nashville business has lumpy cash flow - port-adjacent importers waiting on container releases, restaurants navigating Lower Broadway seasonality, contractors funding payroll between progress draws. Unlike a term loan, you only pay interest on what you draw, and you can pay it back and re-draw without re-applying.",
    "Approval generally requires 6+ months in business, $10K+ monthly revenue and a 600+ personal credit score for the smaller lines. Larger lines ($100K-$500K) typically expect 12+ months of seasoned business banking and 650+ credit. Decisions are usually back within 24-48 hours; first draw arrives the same day for clients on our pre-approved partner programs.",
  ],
  "sba-7a-loan": [
    "The SBA 7(a) program is the SBA's flagship - up to $5 million for working capital, equipment, real estate, business acquisition, refinance or any combination. Nashville borrowers use it most often to either buy a building they currently lease (taking PITI below market rent) or to acquire an existing local business with predictable cash flow.",
    "7(a) loans are made by SBA Preferred Lenders, not by the SBA directly. That distinction matters - lender appetite varies sharply by industry, geography and deal size. The right Preferred Lender for a $400K restaurant acquisition in Belle Meade is rarely the right lender for a $2.4M industrial property in South Nashville. Foxglove Lenders pre-screens and routes. That is most of what we do for SBA files.",
  ],
  "equipment-financing": [
    "Equipment financing uses the equipment itself as the loan's collateral, which makes it one of the easier business loans to qualify for - the lender's downside is recovering the asset. Nashville contractors, restaurants, dental practices and trucking operations use equipment loans to spread the cost over 24-84 months and preserve working capital for operations.",
    "Two structures dominate: equipment loans (you own the asset, build equity, take depreciation) and equipment leases ($1 buyout, fair-market-value or operating lease - each has different tax and balance-sheet implications). For most owner-operated Nashville businesses, an equipment loan with Section 179 depreciation is the simpler, lower-total-cost option. We model both before recommending.",
    "Application is usually fast - invoice or purchase order from the equipment vendor, last 3 months of business bank statements, and a one-page application. Decisions land in 24-48 hours for clean files. Funding can wire directly to the equipment vendor at delivery, which is the cleanest path for both buyer and seller.",
  ],
  "merchant-cash-advance": [
    "Merchant cash advances are not technically loans. They're a purchase of your future receivables at a discount. For Nashville retailers, restaurants and service businesses with strong daily card volume but weaker credit or paperwork, an MCA is sometimes the only product on the table.",
    "Foxglove Lenders is direct with clients about the trade-off: MCAs are fast (24-48 hour funding) and easy to qualify for, but factor rates of 1.25-1.45 mean you're paying $25K-$45K to get $100K, often over 6-12 months. If you can wait 5-10 business days for a working capital or short-term loan, the cost is materially lower. We recommend MCAs only when the timeline and approval profile rule out cheaper options.",
  ],
  "business-acquisition-loans": [
    "Buying an existing Nashville business - restaurant, dental practice, distribution operation, professional services book - is one of the highest-success uses of SBA 7(a) financing. SBA will fund up to 90% of the purchase price (10% buyer equity, sometimes structured as a seller note on standby) with 10-year amortization on goodwill and longer on any real estate involved.",
    "The deal hits or misses on three things: clean trailing 3-year financials from the seller, sufficient cash flow coverage (typically 1.25x debt service after a reasonable owner salary) and an acquirer with industry-relevant experience. We've routed acquisitions of Nashville auto shops, medical practices and I-65 logistics companies. Each has a different short-list of SBA Preferred Lenders most likely to say yes.",
    "Timing matters. SBA acquisition deals typically close in 60-90 days from offer accepted to funded - sometimes faster with a Preferred Lender that has the seller's industry experience. The riskiest stretch is the period between LOI and SBA approval. We recommend conditional-on-financing language in the LOI so the buyer isn't exposed if underwriting comes back differently than expected.",
  ],
  "startup-business-loans": [
    "True startup financing (under 6 months in business, limited revenue, no track record) is the hardest segment to fund. SBA 7(a) can work for owners with strong personal credit, industry experience and 10-20% equity injection. Equipment financing works when the equipment is the loan collateral. Beyond that, most \"startup loans\" are actually personal credit products dressed up - personal loans, 0% APR business credit cards stacked or HELOCs against owner real estate.",
    "We are honest about this with Nashville founders: if you are under 12 months and pre-revenue, the realistic toolkit is SBA (if you qualify), equipment finance (if you have the asset) or personal credit. Anyone promising a \"$250K startup business loan\" with no underwriting is either marketing an MCA or worse. We'll tell you which products you actually qualify for in one call.",
  ],
  "unsecured-business-loans": [
    "Unsecured business loans skip the collateral requirement - no UCC blanket lien on inventory, equipment or receivables. For Nashville service businesses, consulting firms and asset-light operators, that's often the only way the math works: there's no equipment to pledge in the first place.",
    "Lenders compensate for the missing collateral with stricter underwriting - usually 650+ personal credit, 12+ months in business and consistent monthly revenue. Loan amounts typically cap at 1-2x average monthly revenue. Personal guarantees are nearly always required. Approvals can land same-day for clean files; funding follows in 1-3 business days.",
    "Use cases we see most often in Nashville: consulting and professional services firms funding hiring or office moves, software and digital agencies bridging client receivables, and physician or dental practices smoothing payer reimbursement cycles. Foxglove Lenders pre-screens for unsecured-friendly lenders rather than running you through general SBA underwriting that will demand collateral you don't have.",
  ],
  "trucking-business-loans": [
    "Trucking financing in Nashville breaks into three buckets: equipment (tractors and trailers), working capital (insurance down payments, fuel, repair reserves) and AR/factoring (the gap between freight delivery and broker payment). Owner-operators and small fleets running the I-65 corridor between Nashville and Louisville, or the I-65 freight lanes, typically need all three working in concert.",
    "Equipment loans are the easiest part - the truck is the collateral. AR factoring or AR financing handles the 30-60 day broker payment cycle that strangles weekly payroll. Working capital loans handle insurance down payments and unexpected repairs. Foxglove Lenders structures the combination based on rig count, lane mix and customer concentration. The right lender for an owner-operator hauling for one big shipper isn't the right lender for a 15-tractor fleet brokering its own freight.",
  ],
  "restaurant-loans": [
    "Nashville restaurant financing splits along a clean line: equipment-heavy deals (build-outs, second locations, kitchen refreshes) and cash-flow deals (working capital for slow shoulder seasons, payroll bridges, marketing pushes). Equipment financing covers the gear with the equipment as collateral. SBA 7(a) covers acquisitions and major expansion. Working capital lines cover the in-between.",
    "We've routed restaurant deals across Downtown Nashville, The Gulch, 12 South and Green Hills. Each district has a different rent base, customer profile and seasonality - which means the right product mix is different for each. A Gulch chef-driven concept opening a second location is a different SBA 7(a) profile than a Green Hills family restaurant doing a kitchen refresh. Pre-screen always starts with use of funds and operator stage.",
  ],
  "medical-practice-loans": [
    "Medical practice financing - for primary care, specialty practices, surgery centers and clinics - follows a clear playbook: specialty practice-lending banks beat general SBA processing on speed, terms and approval rates. Nashville providers acquiring a practice, expanding a second location or purchasing the real estate they currently lease should start at a specialty desk.",
    "Common Nashville use cases: physician buying into a Green Hills partnership (loan to the individual against future distributions), group acquiring a competing practice (cash flow loan against combined collections), and clinic purchasing equipment for imaging or in-office procedures. Each has a different best-fit lender. The wrong product choice costs 100-200 basis points and 30 days of underwriting.",
    "Surgery centers and ASCs have their own lender pool because the revenue model and equipment intensity are different from a standard medical practice. SBA 7(a) can work for smaller surgical groups; larger centers typically pull from commercial bank specialty desks. Foxglove Lenders routes based on practice type, ownership structure and specific use of funds.",
  ],
  "dental-practice-loans": [
    "Dental practice financing is one of the most competitive lending segments. Dentists default at a fraction of the rate of general small business borrowers, and lenders price accordingly. Nashville dentists routinely qualify for 90-100% acquisition financing on practice buy-ins, full equipment financing on chair upgrades and CBCT scanners, and SBA-backed real estate loans on practice buildings.",
    "Best-fit lenders are typically specialty practice-lending banks (a handful of national players), not general business lenders. They understand the metrics - collections per provider, hygiene revenue percentage, average production per chair - that general lenders treat as opaque. Foxglove Lenders routes directly to those specialty desks rather than starting from a general SBA application.",
    "Practice acquisitions, partner buy-ins and de novo startups each have a different best-fit lender within the specialty-desk world. Acquisitions favor lenders with streamlined practice underwriting. Buy-ins use loans to the individual against future distributions. De novo startups are the hardest, typically reserved for specialists with strong personal credit, classroom experience and an established referral source.",
  ],
  "construction-business-loans": [
    "Construction financing in Nashville splits into two categories - capital for the contractor (working capital, equipment, AR financing on AIA progress billings) and capital for the project (multi-draw construction loans for the building itself). Most Nashville GCs need both: a revolving line to bridge slow-pay owners and progress retainage, plus equipment loans for trucks, lifts and specialty gear.",
    "Construction loans (for the project, not the contractor) are draw-based, interest-only during the build, and typically convert to permanent financing at certificate of occupancy. LTC tops out around 80% on conventional, 75-80% on SBA 504. We've routed both ground-up projects and value-add renovation deals across Davidson County. The mix between bridge and permanent financing matters more than headline rate on most deals.",
  ],
  "oilfield-services-loans": [
    "Industrial services financing in Middle Tennessee serves manufacturing support, field maintenance and infrastructure crews - companies keeping Nissan, GM and the broader distribution network running. Revenue cycles track production schedules and contract renewals, but the capital structure mirrors oilfield: equipment-heavy, receivable-intensive and sensitive to large-customer concentration.",
    "The dominant products are equipment financing (service trucks, specialty rigs and tools, with the gear as collateral), AR factoring or AR financing (to bridge the 30-60 day payment cycle from large-plant customers), and working capital lines for slow quarters. SBA 7(a) can fit acquisitions and partner buy-outs for established service companies with three years of clean financials. Foxglove Lenders pre-screens by customer concentration, equipment base and contract tenure.",
  ],
  "hotel-loans": [
    "Hotel financing in Nashville splits along flag-vs-independent lines and ground-up-vs-acquisition lines. Flagged Lower Broadway and Midtown-area hotels are the cleanest SBA 504 candidates - strong sponsor, brand-mandated PIP, identifiable cash flow. Independent boutique properties typically pull from conventional CRE lenders and bridge financiers willing to underwrite hospitality without a brand cushion.",
    "Common deal types: SBA 7(a) or 504 for acquisitions and PIPs, bridge-to-perm for value-add repositions, and FF&E equipment financing for refresh cycles. LTV tops out around 90% on SBA, 75% on conventional. We've routed hotel deals along the I-65 corridor and the Lower Broadway corridor; the right lender mix depends on flag, rooms count and sponsor experience.",
  ],
  "retail-business-loans": [
    "Retail financing for Nashville storefronts is mostly about three things: inventory (seasonal pre-buys, slow-moving SKUs, vendor terms), build-outs (storefront refreshes, second locations) and working capital (covering the gap between rent, payroll and uneven sales). Inventory lines and working capital cover the day-to-day; equipment financing handles fixtures, POS and refrigeration; SBA 7(a) handles expansion and acquisition.",
    "The Gulch, Green Hills, Opry Mills and the Lower Broadway corridor each have different rent bases and customer profiles. A Gulch boutique opening a second location is a different SBA profile than an Opry Mills anchor tenant doing a refresh. Foxglove Lenders pre-screens by district, AOV and seasonality before recommending the financing mix.",
  ],
  "veteran-business-loans": [
    "Nashville has a deep veteran owner-operator community, with Fort Campbell an hour north and a broad network of military families who've settled across Middle Tennessee. SBA Express financing for veteran-owned businesses carries reduced fees and 36-hour SBA turnaround, which on the right deal beats conventional underwriting by 30+ days.",
    "Common use cases for veteran-owned Nashville businesses: starting a service company after separation, acquiring an established operation as a second career, and bridging contract mobilization before the first government payment hits. Foxglove Lenders pre-screens for veteran-friendly lenders within the SBA Preferred Lender pool and translates DD-214 credentials into underwriting strength rather than treating them as paperwork.",
  ],
  "manufacturing-equipment-financing": [
    "Manufacturing equipment financing covers CNC machines, stamping presses, robotics, conveyor systems and full production cells. For Nashville Tier-2 suppliers feeding Nissan and GM, East Nashville fabricators and BNA corridor aerospace MROs, equipment financing is the primary CapEx vehicle - the equipment is the collateral, and the structure aligns to the ROI timeline of the asset.",
    "Two structures dominate: equipment loans (you own the asset, build equity, take Section 179 depreciation) and equipment leases ($1 buyout, fair-market-value or operating lease - each has different tax and balance-sheet implications). Soft costs (installation, training, freight) can usually be rolled into the financing. Step-payment structures align debt service to the asset's ramp-up curve. Foxglove Lenders models both before recommending.",
  ],
};
