// Long-form body copy per Nashville neighborhood - used by
// nashville.$suburb.tsx to lift pages above the 700-word threshold.

export const SUBURB_BODIES: Record<string, string[]> = {
  "downtown-nashville": [
    "Downtown Nashville is the city's hospitality, tourism and music-industry engine — Lower Broadway's honky-tonks, the Ryman Auditorium, the Country Music Hall of Fame, Bridgestone Arena and a thick base of law firms, music-publishing companies and accounting practices clustered around 4th Avenue and Church Street. Revenue here runs on the bachelorette trade, the convention calendar and the live-music cycle — producing a cash-flow pattern that is deeply event-driven and seasonally front-loaded. Rent and build-out costs along Lower Broadway and the Nashville Yards development run materially above the metro average, which compresses margin and elevates the importance of flexible working capital.",
    "Foxglove Lenders has routed Downtown deals across three recurring patterns: hospitality acquisition financing for operators stepping into Broadway honky-tonk and restaurant concepts, working capital lines that smooth shoulder-season and off-convention-week cash flow, and professional-services partner buy-ins for music-industry law and accounting firms. SBA 7(a) covers most acquisition and partner-buyout work cleanly. SBA 504 fits when a Downtown operator finally buys the building they've leased for a decade. For event-driven food-and-beverage operators, working capital lines cover the gap between fixed lease costs and the uneven monthly revenue tied to Broadway foot traffic and Bridgestone Arena event density.",
  ],
  "germantown": [
    "Germantown is Nashville's historic Victorian district north of Downtown — chef-driven restaurants along Monroe Street and 6th Avenue North, boutique retail, design studios and bed-and-breakfasts, plus First Horizon Park. Rent per square foot in Germantown is among the highest in the metro outside Lower Broadway, which compresses margin for everyone in the district. The neighborhood's preservation overlay keeps build-out costs high and renovation timelines long — every exterior change needs Metro Historic Zoning Commission approval.",
    "Foxglove Lenders routes Germantown deals around build-outs, equipment + working capital combos and SBA 7(a) acquisitions when concept-driven operators transition owners. Restaurant acquisitions here are among our most common closes — the neighborhood's stable foot traffic and strong tourist draw produce underwriting profiles that fit SBA 7(a) at its most competitive pricing tier. For boutique retail and design studios, revenue-based financing handles the seasonality and event-driven sales cycle without forcing a fixed monthly installment against high fixed lease costs. Pre-screen always starts with use of funds and the operator's vintage, because the right lender bench for a Germantown restaurant group differs from the right bench for a design studio.",
  ],
  "twelve-south": [
    "12 South runs along 12th Avenue South — the murals, the Draper James flagship, Sevier Park and a tight corridor of boutique retail, chef-driven restaurants and boutique fitness studios. Foot traffic here is heavy, weekend-skewed and heavily influenced by social-media-driven destination traffic. Revenue patterns lean destination-district rather than neighborhood-retail — a single Instagram post can drive a weekend sales spike that the monthly average can't predict. This is why working capital flexibility matters more here than in flatter suburban markets.",
    "Foxglove Lenders finances 12 South operators with SBA 7(a) acquisitions, equipment financing for restaurants and revenue-based financing for fast-growing boutique brands. Revenue-based financing is the product that fits 12 South's retail and creative operators best — payments flex with the weekend-and-event-driven revenue cycle rather than forcing a fixed installment against a lean-week baseline. For chef-driven concepts scaling from 12 South to a second Nashville location, SBA 7(a) handles the acquisition cleanly at 10% down with goodwill included. Boutique fitness operators along the 12th Avenue corridor use equipment + build-out combos to bring new studios to market without depleting working capital.",
  ],
  "east-nashville": [
    "East Nashville sits across the Cumberland River from Downtown — Five Points, the Lockeland Springs district, breweries along the river and a deep base of chef-driven restaurants, design studios and creative-class boutiques. Operators here trend smaller, more concept-driven and more event-tied than Downtown or Germantown, producing choppier monthly revenue and a higher reliance on flexible working capital. The Five Points corridor in particular has become one of Nashville's most densely creative small-business clusters, mixing food, drink, art and boutique service businesses in close proximity.",
    "Foxglove Lenders routes East Nashville financing across working capital lines, revenue-based financing for breweries and creative shops, and SBA 7(a) when an established concept acquires or expands. Craft brewery equipment financing is a recurring East Nashville pattern — fermenters, canning lines and taproom build-outs with the equipment as collateral. For the design studios and creative agencies along the Lockeland corridor, revenue-based financing provides non-dilutive growth capital sized to monthly revenue. Pre-screen always starts with the operator's cash-flow seasonality, because the right product for an event-tied Five Points bar isn't the right product for a river-adjacent brewery or a creative studio.",
  ],
  "the-gulch": [
    "The Gulch is Nashville's mixed-use mid-rise district south of Downtown — boutique hotels, chef-driven restaurants, design-forward retail and a growing base of tech-enabled professional services in the new office towers. Operators here trend scale-oriented and design-forward, with cleaner underwriting profiles than the event-tied operators in Downtown or East Nashville. The Gulch's pedestrian bridge, proximity to the Music Row talent ecosystem and the Station Inn's legacy have made it one of the most desirable addresses for premium concepts in the metro.",
    "Foxglove Lenders finances Gulch operators with hospitality SBA 7(a), revenue-based financing for tech-enabled services and unsecured lines for professional firms. Boutique hotel acquisitions in the Gulch are a recurring SBA 7(a) pattern — the neighborhood's high ADR and strong occupancy produce underwriting profiles that fit SBA at its most competitive pricing. For tech-enabled service firms in the new Gulch office towers, revenue-based financing provides non-dilutive growth capital for hiring and marketing without a fixed installment tied to unpredictable early-stage revenue. Unsecured working capital lines up to $500K serve the professional-services firms that need growth capital without giving a lender blanket lien exposure on client work product.",
  ],
  "brentwood": [
    "Brentwood sits just south of Nashville along I-65 — a north-Williamson County hub for medical practices, dental groups, specialty clinics and the high-income professional services and retail surrounding them. The patient base is dense, affluent and stable, producing predictable insurance reimbursement cycles and underwriting profiles strong enough to clear SBA 7(a) at its lowest pricing tier. Build-out costs for imaging, surgical suites and specialty clinics in Brentwood run high — practice acquisition deals routinely include $300K–$1M of equipment and remodel inside the same SBA 7(a) close.",
    "Foxglove Lenders has routed Brentwood financing across practice acquisition, partner buy-in, satellite expansion and equipment refresh. SBA 7(a) covers acquisitions and buy-ins up to $5M at 10-year working-capital terms and 25-year real estate amortization. SBA 504 handles owner-occupied medical office building purchases at 10% down — particularly relevant for Brentwood practices that have rented their suite for years and are ready to own. For established Brentwood practices with strong revenue, unsecured working capital lines up to $500K cover equipment refresh, marketing and partner-draw timing without a blanket UCC lien.",
  ],
  "belle-meade": [
    "Belle Meade — an independent municipality inside Nashville's footprint along Harding Pike — concentrates a deep base of independent retail, dental practices and professional services, plus Cheekwood Estate and the Warner Parks. Operators here trend long-tenured and brand-loyal, with strong underwriting profiles built on years of stable patronage from one of Nashville's most affluent residential concentrations. The independent-municipality structure means Belle Meade operators face a separate permitting process from Metro Nashville, which can affect build-out timelines on renovation-heavy projects.",
    "Foxglove Lenders routes Belle Meade financing through SBA 7(a) acquisitions, SBA 504 real estate purchases and unsecured working capital lines. Succession deals dominate the Belle Meade pipeline — several long-established Harding Pike businesses are in second- or third-generation transitions, a high-fit use case for SBA 7(a) with earn-out structures when incoming buyers need to bridge the purchase price gap. For dental and professional-services operators buying the Harding Pike frontage they've leased for a decade, SBA 504 at 10% down finally provides the path to building equity alongside the business.",
  ],
  "franklin": [
    "Franklin sits twenty miles south of Downtown Nashville on I-65 — the historic Main Street district with its Civil War-era storefronts, Carnton Plantation, the CoolSprings Galleria corridor and a steady inflow of relocating households and businesses from across the country. Operators here run two different playbooks side-by-side: boutique and concept-driven on Main Street, corporate-adjacent and scale-oriented in the CoolSprings office park. The divergence means the right financing for a Franklin boutique retailer often looks nothing like the right financing for a CoolSprings B2B service firm.",
    "Foxglove Lenders routes Franklin deals across SBA 7(a) acquisitions for Main Street boutique retail, unsecured working capital for corporate-adjacent service firms and SBA 504 for owner-occupied real estate along both corridors. Main Street acquisitions are recurring — concept-driven operators stepping into established Franklin storefronts use SBA 7(a) at 10% down with goodwill financed. CoolSprings tech and professional-services firms use revenue-based financing for hiring ramps and unsecured lines for business development without a blanket UCC. Pre-screen always starts with the operator's geography within Franklin, because the right lender bench for a Main Street hospitality group differs from the right bench for a CoolSprings corporate-services firm.",
  ],
  "hendersonville": [
    "Hendersonville sits northeast of Nashville on Old Hickory Lake — a fast-growing suburb mixing trades (HVAC, plumbing, electrical), retail along Indian Lake Boulevard and a deep base of family-owned restaurants and boutique services. Operators here trend mid-tenure and growth-oriented, with strong cash-flow profiles built on serving a rapidly expanding residential base. The Indian Lake Boulevard corridor is among the fastest-growing retail strips in the Nashville metro, driven by the sustained household inflow from across Middle Tennessee.",
    "Foxglove Lenders routes Hendersonville financing through equipment lines for trades, SBA 7(a) for franchise QSR expansions and revolving lines for the in-between work. HVAC, plumbing and electrical operators along the I-65 corridor finance trucks and equipment with the rolling stock as collateral — often a straightforward equipment loan structured around the fleet refresh schedule. Franchise QSR operators expanding into a second or third Hendersonville unit use SBA 7(a) at 10% down with the franchise agreement as supporting collateral. For the family-owned restaurant and boutique service operators on Indian Lake Boulevard, revolving working capital lines cover seasonal inventory and the pre-summer build.",
  ],
  "wedgewood-houston": [
    "Wedgewood-Houston (WeHo) sits south of Downtown Nashville — converted industrial lofts, breweries, design studios, art galleries and small-batch food producers. Operators here trend creative-class and equipment-heavy, with revenue patterns that lean seasonal and event-driven. The neighborhood's transformation from industrial corridor to creative district over the past decade has made WeHo one of Nashville's highest-growth small-business clusters — and one of the markets where flexible, equipment-tied financing matters most.",
    "Foxglove Lenders routes WeHo financing through equipment loans for breweries and producers, working capital for creative shops with lumpy cash flow, and revenue-based financing for fast-growing brands. Craft brewery and food-production equipment financing is the most frequent WeHo pattern — fermenters, canning lines, commercial ovens and production cells financed with the equipment as collateral. For the design studios and art galleries with unpredictable monthly revenue, working capital lines that draw and repay against receivables match the cash-flow reality better than a fixed-installment term loan. Revenue-based financing fits WeHo's fast-growing boutique brands that need growth capital without equity dilution.",
  ],
};
