// Long-form body copy per San Antonio neighborhood — used by
// san-antonio.$suburb.tsx to lift pages above the 700-word threshold.
// Mock copy while INDEXABLE=false; the owner can edit freely.

export const SUBURB_BODIES: Record<string, string[]> = {
  "downtown-san-antonio": [
    "Downtown San Antonio is the city's tourism, hospitality and professional-services engine. The Riverwalk, the Convention Center, the Alamo and a thick base of law, accounting and consulting firms create a cash-flow pattern dominated by event volume, conference cycles and tourist seasonality. Rent and build-out costs along Houston, Commerce and the Riverwalk frontage run materially above the city average, which means cash-flow underwriting and bridge structures matter more here than in the suburbs.",
    "Anchor Capital Group has routed Downtown deals across three patterns: hotel CapEx and PIP financing for flagged Riverwalk properties, restaurant working capital lines that smooth shoulder-season cash flow, and professional-services partner buy-in capital — often unsecured and structured around partner draw cycles. SBA 7(a) covers most acquisition and partner-buyout work cleanly. SBA 504 handles owner-occupied real estate purchases when a Downtown firm finally stops renting. For event-driven F&B operators, working capital lines and merchant cash advances cover the gap between fixed lease costs and uneven monthly revenue.",
  ],
  "stone-oak": [
    "Stone Oak is San Antonio's North-side hub for medical practices, dental groups, specialty clinics and the professional services and retail that surround them. The patient base is dense, affluent and stable, which produces predictable insurance reimbursement cycles and underwriting profiles strong enough to clear SBA 7(a) at its lowest stratum of pricing. Build-out costs for imaging, surgical suites and specialty clinics here run high — practice acquisition deals routinely include $300K-$1M of equipment and remodel inside the same SBA 7(a) close.",
    "We've routed Stone Oak financing across practice acquisition, partner buy-in, satellite office expansion and equipment refresh. SBA 7(a) covers acquisitions and buy-ins up to $5M at 10-year working-capital terms and 25-year real estate amortization. SBA 504 handles owner-occupied medical office building purchases at 10% down. For established practices with strong revenue, unsecured working capital lines up to $500K cover equipment, marketing and partner draw timing without a blanket UCC. The pre-screen always starts with use of funds — buying a practice, buying a building, or buying equipment — because the right lender bench is different for each.",
  ],
  "pearl-district": [
    "The Pearl is San Antonio's chef-driven hospitality and boutique-retail district — built around the redeveloped Pearl Brewery, Hotel Emma, the CIA San Antonio campus and the Museum Reach extension of the Riverwalk. Rent per square foot at the Pearl is the highest in the city outside Downtown, which compresses margin and elevates the importance of working capital structure for everyone in the district.",
    "Pearl operators typically need three things at once: build-out capital, equipment financing and working capital that flexes with event-driven sales. Anchor has routed combined SBA 7(a) and equipment-financing structures for chef-driven restaurants opening at the Pearl, equipment-only deals for roasters and brewers expanding production, and revenue-based financing for retailers and creative studios that don't want to take on fixed monthly installments. For hotel projects on the perimeter, SBA 504 plus a bridge structure fits the FF&E + real estate combo cleanly.",
  ],
  "alamo-heights": [
    "Alamo Heights — an independent municipality inside San Antonio's footprint — concentrates a deep base of independent retail, dental practices and professional services along Broadway, plus the Witte Museum, Trinity University and the San Antonio Botanical Garden. Operators here trend more established than the city average, with strong underwriting profiles and a high share of second-generation succession deals.",
    "Acquisition and succession deals dominate the '09 financing pipeline. Several long-established Broadway businesses are now in second- or third-generation transitions — a high-fit use case for SBA 7(a) financing for both incoming family members and outside acquirers. We've routed dental practice acquisitions, retail buy-outs and CPA-firm partner buy-ins through SBA 7(a) at its most competitive pricing. SBA 504 fits when Alamo Heights operators finally buy the Broadway frontage they've leased for a decade. Unsecured working capital lines cover the in-between work — remodels, new equipment, hiring ramps.",
  ],
  southtown: [
    "Southtown is San Antonio's arts and creative district — King William mansions, the Blue Star Arts Complex, the breweries along South Alamo, and the chef-driven restaurants that have made the neighborhood a culinary destination in the past decade. Operators here are smaller, more concept-driven and more event-tied than in Downtown or the Pearl, which produces choppier monthly revenue and a higher reliance on flexible working capital.",
    "Working capital lines and revenue-based financing dominate Southtown's financing mix. For brewers and food producers, equipment financing handles tanks, canning lines and kitchen build-outs with the gear as collateral. For restaurants and bars facing tight monthly cash flow, merchant cash advances and short-term working capital cover the gap between fixed lease and uneven sales. SBA 7(a) still fits established Southtown businesses ready to buy out a partner or finance an acquisition; the pre-screen always starts with the operator's vintage and the use of funds.",
  ],
  westside: [
    "San Antonio's Westside is the cultural and manufacturing heart of the city — a deep base of family-owned panaderías, auto shops, light manufacturers and trades along Guadalupe Street, Commerce and the broader Westside business corridor. Operators here trend long-tenured and family-owned, with strong underwriting profiles built on years of consistent cash flow but often unbanked or underbanked relative to East- and North-side peers.",
    "Anchor Capital Group routes Westside financing across two main patterns: equipment and real estate purchases for legacy operators ready to modernize, and SBA 7(a) acquisitions for second-generation buyers taking over family businesses. Equipment loans cover frame racks, paint booths, CNC equipment and baking lines with the gear as collateral. SBA 504 handles owner-occupied real estate purchases at 10% down — particularly relevant for the Westside operators who've rented the same storefront for two decades. We work hard at the pre-screen stage to translate cash-flow strength into lender-friendly underwriting packages, because the right lender bench for a Westside legacy operator isn't always the obvious one.",
  ],
  "south-san-antonio": [
    "South San Antonio is the industrial backbone of the city — anchored by the Toyota Texas truck plant, Port San Antonio (the redeveloped Kelly AFB), Brooks City Base and a wide base of distribution, manufacturing and aerospace-adjacent suppliers. The commercial mix here is overwhelmingly industrial: equipment financing, SBA 504 owner-occupied real estate and AR-secured working capital cover almost everything we route in the area.",
    "Tier-2 auto suppliers feeding Toyota typically need equipment financing combined with AR factoring or AR-secured lines to bridge the gap between OEM payment cycles and weekly payroll. Aerospace and MRO operators at Port San Antonio finance hangars and ground-support equipment through SBA 504 and specialty equipment financiers familiar with aviation collateral. Distribution and 3PL operators run revolving AR-secured lines or revenue-based financing to scale through peak season. We route based on what the business actually does — the right lender for a Tier-2 stamping shop isn't the right lender for an MRO.",
  ],
  northside: [
    "The I-10 / Loop 1604 Northside corridor concentrates San Antonio's largest employers — USAA, Valero, the South Texas Medical Center and a thick base of tech-enabled professional services. Operators here are typically white-collar, scale-oriented and well-credentialed, which produces clean underwriting profiles and a high fit for unsecured working capital and revenue-based products.",
    "Northside financing patterns lean toward growth capital rather than CapEx. Tech-enabled service firms finance hiring ramps and growth marketing through revenue-based financing — flexible, non-dilutive and aligned to revenue rather than a fixed installment. Medical imaging and specialty practices around the South Texas Medical Center finance equipment refresh and partner buy-ins through SBA 7(a) and equipment-specific lenders. Established consulting and insurance-services firms use unsecured working capital lines up to $500K to fund the kind of growth investments that don't fit on equipment-loan or real-estate structures.",
  ],
  "schertz-cibolo": [
    "Schertz and Cibolo together form the I-35 NE distribution corridor between San Antonio and Austin — Amazon, Sysco and a deep base of franchise food, trades and distribution operators serving the metro from the suburbs. Operators here are typically mid-size and growth-oriented, with strong underwriting profiles built on consistent volumes serving large customers.",
    "Distribution and 3PL operators dominate the I-35 NE financing pipeline. AR financing and factoring cover the gap between large-customer payment cycles and weekly operating costs. Franchise QSR and service-business operators expanding into a second or third unit run SBA 7(a) at 10% down. HVAC, plumbing and electrical operators finance trucks and equipment through equipment loans with the rolling stock as collateral. Anchor routes across all three patterns; the pre-screen starts with the operator's customer concentration and the use of funds.",
  ],
  "new-braunfels": [
    "New Braunfels sits at the north end of the San Antonio metro on the Comal and Guadalupe rivers — a hospitality and tubing-economy town with a growing roster of manufacturers and breweries. Operators here are deeply seasonal: a large share of annual revenue lands in the warm-weather months, which makes the structure of working capital and the timing of debt service materially more important than in flatter markets.",
    "Seasonal working capital lines dominate the New Braunfels financing mix. We've routed lines that flex with the warm-season revenue curve — drawing into spring inventory and paying down through summer cash flow. Hospitality SBA 7(a) handles acquisitions and PIP renovations for Gruene-area and Schlitterbahn-adjacent properties. Equipment financing handles outfitters, river-services operators and manufacturing equipment for the food and beverage producers expanding out of the Hill Country into the broader metro. Pre-screen always starts with seasonality — the right product for a year-round operator is usually wrong for a tubing outfitter.",
  ],
};
