/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanAntonioRouteImport } from './routes/san-antonio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyNowRouteImport } from './routes/apply-now'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanAntonioSuburbRouteImport } from './routes/san-antonio.$suburb'
import { Route as PillarSlugRouteImport } from './routes/pillar.$slug'
import { Route as IndustrySlugRouteImport } from './routes/industry.$slug'
import { Route as SanAntonioSuburbPillarRouteImport } from './routes/san-antonio.$suburb.$pillar'

const SanAntonioRoute = SanAntonioRouteImport.update({
  id: '/san-antonio',
  path: '/san-antonio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNowRoute = ApplyNowRouteImport.update({
  id: '/apply-now',
  path: '/apply-now',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanAntonioSuburbRoute = SanAntonioSuburbRouteImport.update({
  id: '/$suburb',
  path: '/$suburb',
  getParentRoute: () => SanAntonioRoute,
} as any)
const PillarSlugRoute = PillarSlugRouteImport.update({
  id: '/pillar/$slug',
  path: '/pillar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySlugRoute = IndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SanAntonioSuburbPillarRoute = SanAntonioSuburbPillarRouteImport.update({
  id: '/$pillar',
  path: '/$pillar',
  getParentRoute: () => SanAntonioSuburbRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/san-antonio': typeof SanAntonioRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/pillar/$slug': typeof PillarSlugRoute
  '/san-antonio/$suburb': typeof SanAntonioSuburbRouteWithChildren
  '/san-antonio/$suburb/$pillar': typeof SanAntonioSuburbPillarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/san-antonio': typeof SanAntonioRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/pillar/$slug': typeof PillarSlugRoute
  '/san-antonio/$suburb': typeof SanAntonioSuburbRouteWithChildren
  '/san-antonio/$suburb/$pillar': typeof SanAntonioSuburbPillarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/san-antonio': typeof SanAntonioRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/pillar/$slug': typeof PillarSlugRoute
  '/san-antonio/$suburb': typeof SanAntonioSuburbRouteWithChildren
  '/san-antonio/$suburb/$pillar': typeof SanAntonioSuburbPillarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/san-antonio'
    | '/industry/$slug'
    | '/pillar/$slug'
    | '/san-antonio/$suburb'
    | '/san-antonio/$suburb/$pillar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/san-antonio'
    | '/industry/$slug'
    | '/pillar/$slug'
    | '/san-antonio/$suburb'
    | '/san-antonio/$suburb/$pillar'
  id:
    | '__root__'
    | '/'
    | '/apply-now'
    | '/contact'
    | '/san-antonio'
    | '/industry/$slug'
    | '/pillar/$slug'
    | '/san-antonio/$suburb'
    | '/san-antonio/$suburb/$pillar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyNowRoute: typeof ApplyNowRoute
  ContactRoute: typeof ContactRoute
  SanAntonioRoute: typeof SanAntonioRouteWithChildren
  IndustrySlugRoute: typeof IndustrySlugRoute
  PillarSlugRoute: typeof PillarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/san-antonio': {
      id: '/san-antonio'
      path: '/san-antonio'
      fullPath: '/san-antonio'
      preLoaderRoute: typeof SanAntonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-now': {
      id: '/apply-now'
      path: '/apply-now'
      fullPath: '/apply-now'
      preLoaderRoute: typeof ApplyNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-antonio/$suburb': {
      id: '/san-antonio/$suburb'
      path: '/$suburb'
      fullPath: '/san-antonio/$suburb'
      preLoaderRoute: typeof SanAntonioSuburbRouteImport
      parentRoute: typeof SanAntonioRoute
    }
    '/pillar/$slug': {
      id: '/pillar/$slug'
      path: '/pillar/$slug'
      fullPath: '/pillar/$slug'
      preLoaderRoute: typeof PillarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/$slug': {
      id: '/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof IndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-antonio/$suburb/$pillar': {
      id: '/san-antonio/$suburb/$pillar'
      path: '/$pillar'
      fullPath: '/san-antonio/$suburb/$pillar'
      preLoaderRoute: typeof SanAntonioSuburbPillarRouteImport
      parentRoute: typeof SanAntonioSuburbRoute
    }
  }
}

interface SanAntonioSuburbRouteChildren {
  SanAntonioSuburbPillarRoute: typeof SanAntonioSuburbPillarRoute
}

const SanAntonioSuburbRouteChildren: SanAntonioSuburbRouteChildren = {
  SanAntonioSuburbPillarRoute: SanAntonioSuburbPillarRoute,
}

const SanAntonioSuburbRouteWithChildren =
  SanAntonioSuburbRoute._addFileChildren(SanAntonioSuburbRouteChildren)

interface SanAntonioRouteChildren {
  SanAntonioSuburbRoute: typeof SanAntonioSuburbRouteWithChildren
}

const SanAntonioRouteChildren: SanAntonioRouteChildren = {
  SanAntonioSuburbRoute: SanAntonioSuburbRouteWithChildren,
}

const SanAntonioRouteWithChildren = SanAntonioRoute._addFileChildren(
  SanAntonioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyNowRoute: ApplyNowRoute,
  ContactRoute: ContactRoute,
  SanAntonioRoute: SanAntonioRouteWithChildren,
  IndustrySlugRoute: IndustrySlugRoute,
  PillarSlugRoute: PillarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
