/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NashvilleRouteImport } from './routes/nashville'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyNowRouteImport } from './routes/apply-now'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PillarSlugRouteImport } from './routes/pillar.$slug'
import { Route as NashvilleSuburbRouteImport } from './routes/nashville.$suburb'
import { Route as IndustrySlugRouteImport } from './routes/industry.$slug'
import { Route as NashvilleSuburbPillarRouteImport } from './routes/nashville.$suburb.$pillar'

const NashvilleRoute = NashvilleRouteImport.update({
  id: '/nashville',
  path: '/nashville',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNowRoute = ApplyNowRouteImport.update({
  id: '/apply-now',
  path: '/apply-now',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarSlugRoute = PillarSlugRouteImport.update({
  id: '/pillar/$slug',
  path: '/pillar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NashvilleSuburbRoute = NashvilleSuburbRouteImport.update({
  id: '/$suburb',
  path: '/$suburb',
  getParentRoute: () => NashvilleRoute,
} as any)
const IndustrySlugRoute = IndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NashvilleSuburbPillarRoute = NashvilleSuburbPillarRouteImport.update({
  id: '/$pillar',
  path: '/$pillar',
  getParentRoute: () => NashvilleSuburbRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/nashville': typeof NashvilleRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/nashville/$suburb': typeof NashvilleSuburbRouteWithChildren
  '/pillar/$slug': typeof PillarSlugRoute
  '/nashville/$suburb/$pillar': typeof NashvilleSuburbPillarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/nashville': typeof NashvilleRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/nashville/$suburb': typeof NashvilleSuburbRouteWithChildren
  '/pillar/$slug': typeof PillarSlugRoute
  '/nashville/$suburb/$pillar': typeof NashvilleSuburbPillarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/nashville': typeof NashvilleRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/nashville/$suburb': typeof NashvilleSuburbRouteWithChildren
  '/pillar/$slug': typeof PillarSlugRoute
  '/nashville/$suburb/$pillar': typeof NashvilleSuburbPillarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/nashville'
    | '/industry/$slug'
    | '/nashville/$suburb'
    | '/pillar/$slug'
    | '/nashville/$suburb/$pillar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/nashville'
    | '/industry/$slug'
    | '/nashville/$suburb'
    | '/pillar/$slug'
    | '/nashville/$suburb/$pillar'
  id:
    | '__root__'
    | '/'
    | '/apply-now'
    | '/contact'
    | '/nashville'
    | '/industry/$slug'
    | '/nashville/$suburb'
    | '/pillar/$slug'
    | '/nashville/$suburb/$pillar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyNowRoute: typeof ApplyNowRoute
  ContactRoute: typeof ContactRoute
  NashvilleRoute: typeof NashvilleRouteWithChildren
  IndustrySlugRoute: typeof IndustrySlugRoute
  PillarSlugRoute: typeof PillarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nashville': {
      id: '/nashville'
      path: '/nashville'
      fullPath: '/nashville'
      preLoaderRoute: typeof NashvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-now': {
      id: '/apply-now'
      path: '/apply-now'
      fullPath: '/apply-now'
      preLoaderRoute: typeof ApplyNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar/$slug': {
      id: '/pillar/$slug'
      path: '/pillar/$slug'
      fullPath: '/pillar/$slug'
      preLoaderRoute: typeof PillarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nashville/$suburb': {
      id: '/nashville/$suburb'
      path: '/$suburb'
      fullPath: '/nashville/$suburb'
      preLoaderRoute: typeof NashvilleSuburbRouteImport
      parentRoute: typeof NashvilleRoute
    }
    '/industry/$slug': {
      id: '/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof IndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nashville/$suburb/$pillar': {
      id: '/nashville/$suburb/$pillar'
      path: '/$pillar'
      fullPath: '/nashville/$suburb/$pillar'
      preLoaderRoute: typeof NashvilleSuburbPillarRouteImport
      parentRoute: typeof NashvilleSuburbRoute
    }
  }
}

interface NashvilleSuburbRouteChildren {
  NashvilleSuburbPillarRoute: typeof NashvilleSuburbPillarRoute
}

const NashvilleSuburbRouteChildren: NashvilleSuburbRouteChildren = {
  NashvilleSuburbPillarRoute: NashvilleSuburbPillarRoute,
}

const NashvilleSuburbRouteWithChildren = NashvilleSuburbRoute._addFileChildren(
  NashvilleSuburbRouteChildren,
)

interface NashvilleRouteChildren {
  NashvilleSuburbRoute: typeof NashvilleSuburbRouteWithChildren
}

const NashvilleRouteChildren: NashvilleRouteChildren = {
  NashvilleSuburbRoute: NashvilleSuburbRouteWithChildren,
}

const NashvilleRouteWithChildren = NashvilleRoute._addFileChildren(
  NashvilleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyNowRoute: ApplyNowRoute,
  ContactRoute: ContactRoute,
  NashvilleRoute: NashvilleRouteWithChildren,
  IndustrySlugRoute: IndustrySlugRoute,
  PillarSlugRoute: PillarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
